# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('image', models.FileField(upload_to='/flatpage/media/')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
