# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170314_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='catalog.Genre'),
        ),
    ]
