# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 11:15
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170320_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
